version: '2'
services:
  graylog_to_statuspage:
    container_name: graylog_to_statuspage
    build: .
    volumes:
        - config:/var/opt/graylog_to_statuspage/:rw    
volumes:
    config:
        driver: local